name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    
    - uses: extractions/setup-just@v2
    
    - uses: jcbhmr/setup-javy@v1
      with:
        javy-version: '8.0.0'
    
    - uses: sqlc-dev/setup-sqlc@v4
      with:
        sqlc-version: '1.24.0'
    
    - name: Install dependencies
      run: bun install
    
    - name: Build WASM plugin
      run: just plugin-wasm
    
    - name: Test with sqlc
      run: sqlc -f sqlc.dev.yaml diff
      working-directory: examples