name: examples
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  bun-postgresql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: sqlc-dev/action-setup-postgres@master
        with:
          postgres-version: "16"
        id: postgres
      - run: bun install
        working-directory: examples/bun-postgres
      - run: psql -f schema.sql "$DATABASE_URL"
        working-directory: examples/authors/postgresql
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable
      - run: bun run src/main.ts
        working-directory: examples/bun-postgres
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable

  node-postgresql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: sqlc-dev/action-setup-postgres@master
        with:
          postgres-version: "16"
        id: postgres
      - run: npm install
        working-directory: examples/node-postgres
      - run: npx tsc
        working-directory: examples/node-postgres
      - run: psql -f schema.sql "$DATABASE_URL"
        working-directory: examples/authors/postgresql
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable
      - run: node ./src/main.js
        working-directory: examples/node-postgres
        env:
          DATABASE_URL: ${{ steps.postgres.outputs.connection-uri }}?sslmode=disable
